### ISSUE TITLE
Destructing object has error in Eslint 6

### ISSUE THREAD

**Issue by b0939261761** [vuejs/eslint-config-airbnb#2]
Hi,
Destructing object has error in Eslint 6.
Could you update `eslint-config-airbnb-base` package to latest version?

Code:
```js
    selectLocales() {
      const { [this.locale]: active, ...other } = this.locales;
      return other;
    }
```

```bash
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'type' of undefined
Occurred while linting /home/user/ProjectWeb/coffee-print-account-client/src/components/Common/
SelectLanguage.vue:66
    at checkDestructured (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint
/lib/rules/no-useless-rename.js:104:43)
    at listeners.(anonymous function).forEach.listener (/home/user/ProjectWeb/coffee-print-acco
unt-client/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/l
inter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/user/ProjectWeb/coffee-print-account-client/node
_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
    at nodeQueue.forEach.traversalInfo (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/linter.js:935:32)
    at Array.forEach (<anonymous>)
    at runRules (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/linter.js:930:15)
    at Linter._verifyWithoutProcessors (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/linter.js:1132:31)
    at preprocess.map (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/linter.js:1255:29)
    at Array.map (<anonymous>)
    at Linter._verifyWithProcessor (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/linter.js:1250:65)
    at Linter._verifyWithConfigArray (/home/user/ProjectWeb/coffee-print-account-client/node_modules/eslint/lib/linter/linter.js:1222:25)

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Login.vue?vue&type=script&lang=js& 42:0-68 48:20-34

```

package.json

```json
"devDependencies": {
   ...
   "@vue/eslint-config-airbnb": "^4.0.1",
    "eslint": "^6.5.0"
   ...
  }
```

Thank's

**Comment by sodatea** [comment]
Fixed in v5.0.0
